export const quotes = [
  { text: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
  { text: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
  { text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein" },
  { text: "Life is short, and it is up to you to make it sweet.", author: "Sarah Louise Delany" },
  { text: "The unexamined life is not worth living.", author: "Socrates" },
  { text: "Life itself is the most wonderful fairy tale.", author: "Hans Christian Andersen" },
  { text: "Life is a journey, not a destination.", author: "Ralph Waldo Emerson" },
  { text: "Life begins at the end of your comfort zone.", author: "Neale Donald Walsch" },
  { text: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs" },
  { text: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde" },
  { text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
  { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { text: "Opportunities don't happen. You create them.", author: "Chris Grosser" },
  { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
  { text: "If you want to achieve greatness stop asking for permission.", author: "Anonymous" },
  { text: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon" },
  { text: "Dreams don't work unless you do.", author: "John C. Maxwell" },
  { text: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { text: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
  { text: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
  { text: "Strength does not come from physical capacity. It comes from an indomitable will.", author: "Mahatma Gandhi" },
  { text: "The pain you feel today will be the strength you feel tomorrow.", author: "Anonymous" },
  { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
  { text: "Keep going. Everything you need will come to you at the perfect time.", author: "Anonymous" },
  { text: "Don't limit your challenges. Challenge your limits.", author: "Jerry Dunn" },
  { text: "Difficulties in life are intended to make us better, not bitter.", author: "Dan Reeves" },
  { text: "Perseverance is not a long race; it is many short races one after the other.", author: "Walter Elliot" },
  { text: "Never give up on a dream just because of the time it will take to accomplish it.", author: "Earl Nightingale" },
  { text: "Learn as if you will live forever, live like you will die tomorrow.", author: "Mahatma Gandhi" },
  { text: "The beautiful thing about learning is nobody can take it away from you.", author: "B.B. King" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "The expert in anything was once a beginner.", author: "Helen Hayes" },
  { text: "Growth is painful. Change is painful. But nothing is as painful as staying stuck.", author: "N. R. Narayana Murthy" },
  { text: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela" },
  { text: "Change is the end result of all true learning.", author: "Leo Buscaglia" },
  { text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
  { text: "Failure is simply the opportunity to begin again, this time more intelligently.", author: "Henry Ford" },
  { text: "The mind is not a vessel to be filled but a fire to be kindled.", author: "Plutarch" },
  { text: "Innovation distinguishes between a leader and a follower.", author: "Steve Jobs" },
  { text: "Creativity is intelligence having fun.", author: "Albert Einstein" },
  { text: "Think big and don't listen to people who tell you it can't be done.", author: "Tim Ferriss" },
  { text: "Logic will get you from A to B. Imagination will take you everywhere.", author: "Albert Einstein" },
  { text: "The best way to predict the future is to invent it.", author: "Alan Kay" },
  { text: "Every artist was first an amateur.", author: "Ralph Waldo Emerson" },
  { text: "Discovery consists of seeing what everybody has seen and thinking what nobody has thought.", author: "Albert Szent-Györgyi" },
  { text: "Great minds discuss ideas; average minds discuss events; small minds discuss people.", author: "Eleanor Roosevelt" },
  { text: "Without deviation from the norm, progress is not possible.", author: "Frank Zappa" },
  { text: "Dare to be naïve.", author: "Buckminster Fuller" },
  { text: "Know thyself.", author: "Socrates" },
  { text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
  { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
  { text: "You must do the thing you think you cannot do.", author: "Eleanor Roosevelt" },
  { text: "The only limits that exist are the ones in your own mind.", author: "Anonymous" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { text: "The only way to be truly satisfied is to do what you believe is great work.", author: "Steve Jobs" },
  { text: "He who conquers himself is the mightiest warrior.", author: "Confucius" },
  { text: "Don't compromise yourself – you're all you have.", author: "Janis Joplin" },
  { text: "Peace comes from within. Do not seek it without.", author: "Buddha" },
  { text: "Where there is love there is life.", author: "Mahatma Gandhi" },
  { text: "Love all, trust a few, do wrong to none.", author: "William Shakespeare" },
  { text: "In the end, the love you take is equal to the love you make.", author: "The Beatles" },
  { text: "You always gain by giving love.", author: "Reese Witherspoon" },
  { text: "Love isn't something you find. Love is something that finds you.", author: "Loretta Young" },
  { text: "The best thing to hold onto in life is each other.", author: "Audrey Hepburn" },
  { text: "Spread love everywhere you go.", author: "Mother Teresa" },
  { text: "Love is composed of a single soul inhabiting two bodies.", author: "Aristotle" },
  { text: "To love and be loved is to feel the sun from both sides.", author: "David Viscott" },
  { text: "We accept the love we think we deserve.", author: "Stephen Chbosky" },
  { text: "Silence is a source of great strength.", author: "Lao Tzu" },
  { text: "The quieter you become, the more you can hear.", author: "Ram Dass" },
  { text: "Patience is bitter, but its fruit is sweet.", author: "Jean-Jacques Rousseau" },
  { text: "A calm mind brings inner strength and self-confidence.", author: "Dalai Lama" },
  { text: "Worry does not empty tomorrow of its sorrow. It empties today of its strength.", author: "Corrie ten Boom" },
  { text: "Stillness is not the absence of movement but the presence of peace.", author: "Anonymous" },
  { text: "Sometimes the most productive thing you can do is relax.", author: "Mark Black" },
  { text: "Don't cry because it's over, smile because it happened.", author: "Dr. Seuss" },
  { text: "The most wasted of all days is one without laughter.", author: "E. E. Cummings" },
  { text: "Be like a tree. Stay grounded. Connect with your roots.", author: "Anonymous" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Make each day your masterpiece.", author: "John Wooden" },
  { text: "Light tomorrow with today.", author: "Elizabeth Barrett Browning" },
  { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
  { text: "The best revenge is massive success.", author: "Frank Sinatra" },
  { text: "Act without expectation.", author: "Lao Tzu" },
  { text: "A goal without a plan is just a wish.", author: "Antoine de Saint-Exupéry" },
  { text: "Don't count the days, make the days count.", author: "Muhammad Ali" },
  { text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair" },
  { text: "You were born to be real, not to be perfect.", author: "Anonymous" }
]; 